### ISSUE TITLE
To-Do List Before Midterm 1 Report

### ISSUE THREAD

**Issue by kemaltulum** [kemaltulum/bouncmpe-senior-project#10]
- [ ] Update project description
- [ ] Create UML Diagram
- [ ] Create Sequence Diagrams
- [ ] Add Collapsible Tree visualization
- [ ] Create User Stories
