### ISSUE TITLE
Project Initialization: To-Do List

### ISSUE THREAD

**Issue by kemaltulum** [kemaltulum/bouncmpe-senior-project#4]
- [ ] List the type of visualizations that will be used in the project
- [ ] Put user story data to graph database
- [ ] Draw component diagram
- [ ] Complete project description
